let modelsJson = [
     
    //BLUSAS
    {id:0, name:'Oakley Canguru - Black', img:'img.blu/blu8.png', price:[105.00, 150.00, 200.00],
    sizes:['P', 'M', 'G'], description:'Blusa Lancamento na cor Preta.'},
    {id:1, name:'Oakley Mark || - White', img:'img.blu/blu10.jpg', price:[110.00, 150.00, 200.00],
    sizes:['P', 'M', 'G'], description:'Blusa social Oakley Lancamento.'},
    {id:2, name:'Moletom Oakley - White', img:'img.blu/blu11.jpg', price:[115.00, 150.00, 200.00],
    sizes:['P', 'M', 'G'], description:'Moletom Oakley cor Branca lancamento.'},
    {id:3, name:'Blusa Oakley Preta', img:'img.blu/blu3.jpg', price:[120.00, 150.00, 200.00],
    sizes:['P', 'M', 'G'], description:'Blusa social Oakley Lancamento.'},
    {id:4, name:'Blusa Oakley Preta', img:'img.blu/blu5.jpg', price:[130.00, 150.00, 200.00],
    sizes:['P', 'M', 'G'], description:'Bluca social Oakley Lancamento.'},
    //BOTAS
    {id:6, name:'Oakley Stratus - Brown', img:'img.bot/b1.jpg', price:[650.00],
    sizes:['38/39', '40/41', '42/43'], description:'Bota modelo Stratus Lancamento.'},
    {id:7, name:'Oakley Half 2.0 - Brown', img:'img.bot/b2.jpg', price:[450.00],
    sizes:['38/39', '40/41', '42/43'], description:'Half 2.0 Lancamento.'},
    {id:8, name:'Oakley Half 2.0 - White', img:'img.bot/b3.jpg', price:[500.00],
    sizes:['38/39', '40/41', '42/43'], description:'Half Branca Lancamento.'},
    {id:9, name:'Oakley Half 2.0 - Black', img:'img.bot/b4.jpg', price:[750.00],
    sizes:['38/39', '40/41', '42/43'], description:'Half Preta Lancamento.'},
    {id:10, name:'Oakley Half 2.0 - Brown', img:'img.bot/b5.jpg', price:[850.00],
    sizes:['38/39', '40/41', '42/43'], description:'Half Marrom Lancamento'},
    //FLACK
    {id:11, name:'Oakley Half - Gold', img:'img.oc/oc14.jpg', price:[1110.00],
    sizes:['Gold', 'Grenn', 'Red'], description:'HalfJacket 2.0 nas lentes Gold.'},
    {id:12, name:'Oakley Flak - Black', img:'img.oc/oc15.jpg', price:[1120.00],
    sizes:['Ice', 'Coffe', 'Esmerald'], description:'Flak nas lente Black.'},
    {id:13, name:'Oakley Half- Red', img:'img.oc/oc12 - Copia.jpg', price:[1155.00],
    sizes:['Blue', 'White', 'Fire'], description:'Half nas lenter Red.'},
    {id:14, name:'Oakley Radar - Blue', img:'img.oc/oc16.jpg', price:[1180.00],
    sizes:['Black', 'Slate', 'Green'], description:'Radar lancamento nas lentes Blue.'},
    {id:15, name:'Oakley Radar - Black', img:'img.oc/oc17.jpg', price:[1140.00],
    sizes:['Ice', 'Red', 'Slate'], description:'Radar Lancamento nas lentes Black'},
    //JULIET
    {id:16, name:'24K - Gold', img:'img.juli/24k.png', price:[5.050],
    sizes:['Ice', 'Red', 'Slate'], description:'Juliet 24k lentes Gold.'},
    {id:17, name:'Mars - Black', img:'img.juli/mars.png', price:[12.550],
    sizes:['Black', 'Slate', 'Green'], description:'Mars nas lentes Black.'},
    {id:18, name:'Romeo1 - Coffee', img:'img.juli/r1.png', price:[3.450],
    sizes:['Blue', 'White', 'Fire'], description:'Romeo1 nas lentes Caffe.'},
    {id:19, name:'Romeo2 - Slate', img:'img.juli/romeo2.png', price:[4.350],
    sizes:['Ice', 'Coffe', 'Esmerald'], description:'Romeo2 nas lentes Slate.'},
    {id:20, name:'X-Metal - Fire', img:'img.juli/xmetal.png', price:[2.050],
    sizes:['Gold', 'Grenn', 'Red'], description:'X-metal nas lentes Fire.'},
    {id:21, name:'X-Metal Green - Lemon', img:'img.juli/xmetal2.png', price:[2.550],
    sizes:['Gold', 'Grenn', 'Red'], description:'X-metal nas lentes lemon.'},
    {id:22, name:'X-Squared - Ice', img:'img.juli/xquared.png', price:[1.550],
    sizes:['Ice', 'Coffe', 'Esmerald'], description:'X-squared nas lentes Ice.'},
    {id:23, name:'Juliet Carbon - Red Violet', img:'img.oc/oc16.jpg', price:[2.550],
    sizes:['Black', 'Slate', 'Green'], description:'Juliet Carbon nas lentes Red.'},
    {id:24, name:'Juliet Penny - Red', img:'img.juli/penny.png', price:[4.450],
    sizes:['Black', 'Slate', 'Green'], description:'Penny nas lentes Red'},
];